### ISSUE TITLE
大神问下 如果只想用单次定位功能的话  能只引入单一的pod吗？管理类会报错吗？

### ISSUE THREAD

**Issue by liubang0909** [deng690990/SF_GaoDeMAP#5]
只是单次定位功能的话  引入这个是不是大材小用了。。

**Comment by deng690990** [comment]
报错倒是不会，只是你的项目体积会相对大一点，你可以只导入官方的SDK，这样更好一些，官方文档也比较详细


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deng690990/SF_GaoDeMAP"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 中午11:05
收件人:&nbsp;"deng690990/SF_GaoDeMAP"<SF_GaoDeMAP@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[deng690990/SF_GaoDeMAP] 大神问下 如果只想用单次定位功能的话  能只引入单一的pod吗？管理类会报错吗？ (#5)





 
只是单次定位功能的话  引入这个是不是大材小用了。。

**Comment by liubang0909** [comment]
好的。。我主要是感觉多个地方用的话 总是判断权限。。能有个封装的就好了  感谢回复。。

**Comment by deng690990** [comment]
这个判断权限是指判断系统是否开启定位权限吗，假如是这个，，你用一个工具类简单封装一下就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liubang0909"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 下午2:47
收件人: "deng690990/SF_GaoDeMAP"<SF_GaoDeMAP@noreply.github.com&gt;; 
抄送: "计科3班邓升发"<164100551@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [deng690990/SF_GaoDeMAP] 大神问下 如果只想用单次定位功能的话  能只引入单一的pod吗？管理类会报错吗？ (#5)





 
好的。。我主要是感觉多个地方用的话 总是判断权限。。能有个封装的就好了  感谢回复。。

**Comment by liubang0909** [comment]
嗯嗯 好的👌
